### ISSUE TITLE
可以在readme中说一下需要用到requests

### ISSUE THREAD

**Issue by ChellyL** [StardustRevelry/esjzoneBackup#1]
作者你好，感谢你制作这个脚本，让我成功备份到了小说，我是在vps上跑这个脚本的，第一次运行时因为没有安装requests而报错，建议增加一个requirement文件写一下需要的库，在vps上使用时方便安装库，或在readme中说一下需要提前安装的库。

**Comment by StardustRevelry** [comment]
感谢支持，requirements已更新
